name: artist
channels:
  - conda-forge
  - ome
  - fastai
  - bioconda
dependencies:
  - numpy>=1.26.0
  - zarr>=3.0.0
  - Pillow
  - flask
  - waitress
  - flask_cors
  - matplotlib
  - tifffile
  - imagecodecs
  - scikit-image
  - pandas
  - pooch
  - cython
  - pyinstaller
  - altair
  - umap-learn
  - scikit-learn
  - colormath
  - h5py
  - bioformats2raw=0.4.0
  - raw2ometiff
  - pip
  - imagemagick
  - tiffslide=2.1.2
  - libvips
  - estimagic
  - pyvips
  - pip:
      - openslide-python
      - opencv-python-headless
      - synapseclient
      - mantel
      - "ome_types>=0.4.2"
      - git+https://github.com/labsyspharm/minerva-lib-python@master#egg=minerva-lib
