# Conda environment for nf-artist with pinned dependencies
name: artist
channels:
  - conda-forge
  - ome
  - fastai
  - bioconda
dependencies:
  - numpy>=1.23.0,<2.0
  - zarr=2.6.1
  - Pillow
  - flask
  - waitress
  - flask_cors
  - matplotlib
  - tifffile
  - imagecodecs
  - scikit-image
  - pandas
  - pooch
  - cython
  - pyinstaller
  - altair
  - umap-learn
  - scikit-learn
  - colormath
  - h5py
  - bioformats2raw
  - raw2ometiff
  - pip
  - imagemagick
  - tiffslide=2.1.2
  - libvips
  - estimagic
  - pyvips
  - pip
